services:
  - type: web
    name: sunspotter-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: WEATHER_API_KEY
        sync: false
    healthCheckPath: /api/health