services:
  # Backend API service
  - type: web
    name: sunspotter-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: CORS_ORIGIN
        value: https://sunspotter-web.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
    healthCheckPath: /api/health

  # Frontend static site
  - type: web
    name: sunspotter-web
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true